### PR TITLE
[Input Number] Min value fixed

### LINKED ISSUE #316: [InputNumber] Min value possible issue when deleting field
Take the Min Max example story for `InputNumber` component.

```
<InputNumber
  dataCy="input-number"
  label="Label"
  maxValue={10}
  minValue={1}
  onChange={function noRefCheck(){}}
  value={5}
/>
```

Check if when removing the value the min value remains or if user is able to write any number.
In case not possible, find a way to let users reset the field value.

CC: @erosval

### PR DESCRIPTION
**Pull request by CrisGrud**
This PR closes #316

### CODE REVIEW

File: src/components/InputNumber/index.tsx [hunk 1]
```diff
@@ -61,6 +86,11 @@ const InputNumber: FC<IInputNumber> = ({
 
   return (
     <MUITextField
+      onKeyDown={(e) => {
+        if (e.key === "e" || e.key === "E" || e.key === "-" || e.key === "+") {
+          e.preventDefault();
+        }
+      }}
```
Comment (luciob) [inline src/components/InputNumber/index.tsx:93]: Define one useCallback method for this

File: src/components/InputNumber/index.tsx [hunk 2]
```diff
@@ -41,16 +41,41 @@ const InputNumber: FC<IInputNumber> = ({
       if (isNaN(numericValue)) {
         return null;
       }
+      const minValueString = minValue.toString();
+      if (minValueString.length > value.length) {
+        return numericValue;
+      }
```
Comment (luciob) [inline src/components/InputNumber/index.tsx:47]: Here at this point you can simply compare if the value is lower, no more need to check the length of the strings since the check on minimum value is done when `blur` event occurs

**Review by luciob — CHANGES_REQUESTED** [review]

**Review by luciob — APPROVED** [review]
